name: CI

env:
  HUSKY: '0' # disable husky

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test on node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        # node: [20, 22]
        node: [22]
        # os: [ubuntu-latest, macOS-latest, windows-latest]
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Cache jest
        uses: actions/cache@v4
        with:
          path: .jest-cache
          key: ${{ runner.os }}-${{ matrix.node }}-jest

      - name: Install dependencies
        run: pnpm install

      - name: lint
        run: pnpm run lint

      - name: build
        run: pnpm run build

      - name: install package revision
        run: pnpm i . -g

      - name: test
        run: pnpm test -u
        continue-on-error: true
        env:
          FORCE_EXIT: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        env:
          HUSKY: '0' # disable husky

      - name: upload visual diff
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: visual-test-diff-${{ runner.os }}-${{ matrix.node }}
          path: temp/diff/*

  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-commit-lint@v1

  auto-merge:
    if: ${{ false }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: rebase
